=== karlkras/quote_tool/ballpark.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT BALLPARK (LANGUAGES,HEADER)>

<!ELEMENT LANGUAGES (LANGUAGE+)>

<!ELEMENT HEADER (DATE, REP, CLIENT, PROJECT)>
<!ELEMENT DATE EMPTY>
<!ATTLIST DATE DATE CDATA #REQUIRED>
<!ELEMENT REP EMPTY>
<!ATTLIST REP REPRESENTATIVE CDATA #REQUIRED>
<!ELEMENT CLIENT EMPTY>
<!ATTLIST CLIENT NAME CDATA #REQUIRED>

<!ELEMENT PROJECT (NAME,PROJTYPE+,FILETYPE,DELIVERABLE,SRCLANG,STARTDATE, RUSHFEE,NOTES)>
<!ELEMENT NAME EMPTY>
<!ATTLIST NAME NAME CDATA #REQUIRED>
<!ELEMENT PROJTYPE EMPTY>
<!ATTLIST PROJTYPE TYPE CDATA #REQUIRED>
<!ELEMENT FILETYPE EMPTY>
<!ATTLIST FILETYPE TYPE CDATA #REQUIRED>
<!ELEMENT DELIVERABLE EMPTY>
<!ATTLIST DELIVERABLE TYPE CDATA #REQUIRED>
<!ELEMENT SRCLANG EMPTY>
<!ATTLIST SRCLANG TYPE CDATA #REQUIRED>
<!ELEMENT STARTDATE EMPTY>
<!ATTLIST STARTDATE DATE CDATA #REQUIRED>
<!ELEMENT RUSHFEE (#PCDATA)>
<!ELEMENT NOTES (#PCDATA)>

<!ELEMENT LANGUAGE (WORDCOUNT,DTP,ENGINEERING,QA,ADDITIONAL,PM,TOTAL)>
<!ATTLIST LANGUAGE NAME CDATA #REQUIRED>
<!ELEMENT WORDCOUNT (NEWTEXT,FUZZYMATCH,REPS)>
<!ELEMENT DTP (FORMATTING)>
<!ELEMENT ENGINEERING (TMWORK,ENG,SCAPS,GRAPHICS)>
<!ELEMENT QA (QUALASR)>
<!ELEMENT ADDITIONAL (ADD1,ADD2,ADD3)>
<!ELEMENT PM (PROJMANG)>
<!ELEMENT TOTAL (TOTALCOST, CALCSELL, ACTSELL, GM)>

<!ELEMENT NEWTEXT (NUMUNIT,COSTPERUNIT,COST,MARKUP,CALCSELL,ACTSELLPER,ACTSELL,GM)>
<!ELEMENT FUZZYMATCH (NUMUNIT,COSTPERUNIT,COST,MARKUP,CALCSELL,ACTSELLPER,ACTSELL,GM)>
<!ELEMENT REPS (NUMUNIT,COSTPERUNIT,COST,MARKUP,CALCSELL,ACTSELLPER,ACTSELL,GM)>
<!ELEMENT FORMATTING (NUMUNIT,COSTPERUNIT,COST,MARKUP,CALCSELL,ACTSELLPER,ACTSELL,GM)>
<!ELEMENT TMWORK (NUMUNIT,COSTPERUNIT,COST,MARKUP,CALCSELL,ACTSELLPER,ACTSELL,GM)>
<!ELEMENT ENG (NUMUNIT,COSTPERUNIT,COST,MARKUP,CALCSELL,ACTSELLPER,ACTSELL,GM)>
<!ELEMENT SCAPS (NUMUNIT,COSTPERUNIT,COST,MARKUP,CALCSELL,ACTSELLPER,ACTSELL,GM)>
<!ELEMENT GRAPHICS (NUMUNIT,COSTPERUNIT,COST,MARKUP,CALCSELL,ACTSELLPER,ACTSELL,GM)>
<!ELEMENT QUALASR (NUMUNIT,COSTPERUNIT,COST,MARKUP,CALCSELL,ACTSELLPER,ACTSELL,GM)>
<!ELEMENT ADD1 (COST,MARKUP,ACTSELL,GM)>
<!ELEMENT ADD2 (COST,MARKUP,ACTSELL,GM)>
<!ELEMENT ADD3 (COST,MARKUP,ACTSELL,GM)>
<!ELEMENT PROJMANG (NUMUNIT,COSTPERUNIT,COST,MARKUP,CALCSELL,ACTSELL,GM)>

<!ELEMENT TOTALCOST (#PCDATA)>
<!ELEMENT CALCSELL (#PCDATA)>
<!ELEMENT ACTSELL (#PCDATA)>
<!ELEMENT GM (#PCDATA)>
<!ELEMENT NUMUNIT (#PCDATA)>
<!ELEMENT COSTPERUNIT (#PCDATA)>
<!ELEMENT COST (#PCDATA)>
<!ELEMENT MARKUP (#PCDATA)>
<!ELEMENT ACTSELLPER (#PCDATA)>

=== karlkras/quote_tool/original.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE BALLPARK SYSTEM "C:\Documents and Settings\mikevg\My Documents\Lingo Website\estimator\ballpark.dtd">
<BALLPARK>
	<LANGUAGES>
		<LANGUAGE NAME="Arabic">
			<WORDCOUNT>
				<NEWTEXT>
					<NUMUNIT>119</NUMUNIT>
					<COSTPERUNIT>0.19</COSTPERUNIT>
					<COST>22.61</COST>
					<MARKUP>40</MARKUP>
					<CALCSELL>0.316666</CALCSELL>
					<ACTSELLPER>0.32</ACTSELLPER>
					<ACTSELL>38.08</ACTSELL>
					<GM>41</GM>
				</NEWTEXT>
				<FUZZYMATCH>
					<NUMUNIT>0</NUMUNIT>
					<COSTPERUNIT>0.19</COSTPERUNIT>
					<COST>0</COST>
					<MARKUP>40</MARKUP>
					<CALCSELL/>
					<ACTSELLPER>0</ACTSELLPER>
					<ACTSELL>0</ACTSELL>
					<GM>0</GM>
				</FUZZYMATCH>
				<REPS>
					<NUMUNIT>4</NUMUNIT>
					<COSTPERUNIT>0.19</COSTPERUNIT>
					<COST>0.76</COST>
					<MARKUP>40</MARKUP>
					<CALCSELL>0.316666</CALCSELL>
					<ACTSELLPER>0.32</ACTSELLPER>
					<ACTSELL>1.28</ACTSELL>
					<GM>41</GM>
				</REPS>
			</WORDCOUNT>
			<DTP>
				<FORMATTING>
					<NUMUNIT>0.00</NUMUNIT>
					<COSTPERUNIT>27</COSTPERUNIT>
					<COST>0</COST>
					<MARKUP>40</MARKUP>
					<CALCSELL/>
					<ACTSELLPER>0</ACTSELLPER>
					<ACTSELL>0</ACTSELL>
					<GM>0</GM>
				</FORMATTING>
			</DTP>
			<ENGINEERING>
				<TMWORK>
					<NUMUNIT/>
					<COSTPERUNIT>33</COSTPERUNIT>
					<COST>0</COST>
					<MARKUP>40</MARKUP>
					<CALCSELL/>
					<ACTSELLPER>0</ACTSELLPER>
					<ACTSELL>0</ACTSELL>
					<GM>0</GM>
				</TMWORK>
				<ENG>
					<NUMUNIT/>
					<COSTPERUNIT>33</COSTPERUNIT>
					<COST>0</COST>
					<MARKUP>40</MARKUP>
					<CALCSELL/>
					<ACTSELLPER>0</ACTSELLPER>
					<ACTSELL>0</ACTSELL>
					<GM>0</GM>
				</ENG>
				<SCAPS>
					<NUMUNIT>0.00</NUMUNIT>
					<COSTPERUNIT>33</COSTPERUNIT>
					<COST>0</COST>
					<MARKUP>40</MARKUP>
					<CALCSELL/>
					<ACTSELLPER>0</ACTSELLPER>
					<ACTSELL>0</ACTSELL>
					<GM>0</GM>
				</SCAPS>
				<GRAPHICS>
					<NUMUNIT>0.00</NUMUNIT>
					<COSTPERUNIT>33</COSTPERUNIT>
					<COST>0</COST>
					<MARKUP>40</MARKUP>
					<CALCSELL/>
					<ACTSELLPER>0</ACTSELLPER>
					<ACTSELL>0</ACTSELL>
					<GM>0</GM>
				</GRAPHICS>
			</ENGINEERING>
			<QA>
				<QUALASR>
					<NUMUNIT>0.00</NUMUNIT>
					<COSTPERUNIT>25</COSTPERUNIT>
					<COST>0</COST>
					<MARKUP>40</MARKUP>
					<CALCSELL/>
					<ACTSELLPER>0</ACTSELLPER>
					<ACTSELL>0</ACTSELL>
					<GM>0</GM>
				</QUALASR>
			</QA>
			<ADDITIONAL>
				<ADD1>
					<COST>1</COST>
					<MARKUP>40</MARKUP>
					<ACTSELL>0</ACTSELL>
					<GM>0</GM>
				</ADD1>
				<ADD2>
					<COST>1</COST>
					<MARKUP>40</MARKUP>
					<ACTSELL>0</ACTSELL>
					<GM>0</GM>
				</ADD2>
				<ADD3>
					<COST>1</COST>
					<MARKUP>40</MARKUP>
					<ACTSELL>0</ACTSELL>
					<GM>0</GM>
				</ADD3>
			</ADDITIONAL>
			<PM>
				<PROJMANG>
					<NUMUNIT/>
					<COSTPERUNIT>26</COSTPERUNIT>
					<COST>0</COST>
					<MARKUP/>
					<CALCSELL>0</CALCSELL>
					<ACTSELL>0</ACTSELL>
					<GM>0</GM>
				</PROJMANG>
			</PM>
			<TOTAL>
				<TOTALCOST>23.37</TOTALCOST>
				<CALCSELL>0.63</CALCSELL>
				<ACTSELL>39.36</ACTSELL>
				<GM>40.62</GM>
			</TOTAL>
		</LANGUAGE>
	</LANGUAGES>
	<HEADER>
		<DATE DATE="Nov 10, 2009"/>
		<REP REPRESENTATIVE="Ann Chay"/>
		<CLIENT NAME="Juniper"/>
		<PROJECT>
			<NAME NAME=""/>
			<PROJTYPE TYPE="Website"/>
			<FILETYPE TYPE="Word"/>
			<DELIVERABLE TYPE=""/>
			<SRCLANG TYPE="English (US)"/>
			<STARTDATE DATE=""/>
			<RUSHFEE>rf0</RUSHFEE>
			<NOTES/>
		</PROJECT>
	</HEADER>
</BALLPARK>
